apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  ports:
    - name: "udagram-user-api"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: udagram-restapi-user
