apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: udagram-reverseproxy
