apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  type: LoadBalancer
  ports:
    - name: "udagram-api"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: udagram-reverseproxy
