apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  ports:
    - name: "udagram-feed-api"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: udagram-restapi-feed
