apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: "udagram-ui"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: udagram-frontend
