apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  UDCD_POSTGRES_USERNAME: {{UDCD_POSTGRES_USERNAME_BASE64}}
  UDCD_POSTGRES_PASSWORD: {{UDCD_POSTGRES_PASSWORD_BASE64}}
  UDCD_JWT_SECRET: {{UDCD_JWT_SECRET_BASE64}}
