# kubectl apply -f udagram-secret-env.yml
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  UDCD_POSTGRES_USERNAME: TO_BE_REPLACED_BY_BASE64_ENCODED
  UDCD_POSTGRES_PASSWORD: TO_BE_REPLACED_BY_BASE64_ENCODED
  UDCD_JWT_SECRET: TO_BE_REPLACED_BY_BASE64_ENCODED
