version: '3.7'

services:
  backend-feed:
    container_name: 'udagram-backend-feed'
    image: maloufde/udagram-restapi-feed:1.0.0
    build:
      context: ../../udacity-c3-restapi-feed
    environment:
      - UDCD_POSTGRES_USERNAME
      - UDCD_POSTGRES_PASSWORD
      - UDCD_POSTGRES_DATABASE
      - UDCD_POSTGRES_HOST
      - UDCD_AWS_REGION
      - UDCD_AWS_PROFILE
      - UDCD_AWS_MEDIA_BUCKET
      - UDCD_JWT_SECRET
      - UDCD_CORS_ALLOW
    volumes:
      - type: bind
        source: ${UDCD_AWS_CREDENTIALS}
        target: /home/node/.aws
        read_only: true

  backend-user:
    container_name: 'udagram-backend-user'
    image: maloufde/udagram-restapi-user:1.0.0
    build:
      context: ../../udacity-c3-restapi-user
    environment:
      - UDCD_POSTGRES_USERNAME
      - UDCD_POSTGRES_PASSWORD
      - UDCD_POSTGRES_DATABASE
      - UDCD_POSTGRES_HOST
      - UDCD_AWS_REGION
      - UDCD_AWS_PROFILE
      - UDCD_AWS_MEDIA_BUCKET
      - UDCD_JWT_SECRET
      - UDCD_CORS_ALLOW

  reverseproxy:
    image: maloufde/udagram-reverseproxy:1.0.0
    build:
      context: ./nginx
    container_name: 'udagram-reverseproxy'
    depends_on:
      - backend-feed
      - backend-user
    ports:
      - "8080:8080"

  frontend:
    image: maloufde/udagram-frontend:1.0.1
    build:
      context: ../../udacity-c3-frontend
    container_name: 'udagram-frontend'
    ports:
      - "8100:80"
