version: '3.7'

services:
  backend-feed:
    container_name: 'udagram-backend-feed'
    image: maloufde/udagram-restapi-feed
    build:
      context: ../../udacity-c3-restapi-feed
    environment:
      - UDCD_POSTGRES_USERNAME
      - UDCD_POSTGRES_PASSWORD
      - UDCD_POSTGRES_DATABASE
      - UDCD_POSTGRES_HOST
      - UDCD_AWS_REGION
      - UDCD_AWS_PROFILE
      - UDCD_AWS_MEDIA_BUCKET
      - UDCD_JWT_SECRET

  backend-user:
    container_name: 'udagram-backend-user'
    image: maloufde/udagram-restapi-user
    build:
      context: ../../udacity-c3-restapi-user
    environment:
      - UDCD_POSTGRES_USERNAME
      - UDCD_POSTGRES_PASSWORD
      - UDCD_POSTGRES_DATABASE
      - UDCD_POSTGRES_HOST
      - UDCD_AWS_REGION
      - UDCD_AWS_PROFILE
      - UDCD_AWS_MEDIA_BUCKET
      - UDCD_JWT_SECRET

  reverseproxy:
    image: maloufde/udagram-reverseproxy
    build:
      context: ./nginx
    container_name: 'udagram-reverseproxy'
    depends_on:
      - backend-feed
      - backend-user
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
